version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      MODSECURITY_ENABLED: "true"
    depends_on:
      - "nginx"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/modsecurity.d:/etc/nginx/modsecurity.d
